### PR TITLE
feat(docker): add docker support

### PR DESCRIPTION
**Pull request by uZer**
Hi there,
Thanks for your work!
I've added a docker container for this project. You can use it with docker-compose and/or aliases. Documentation has been updated accordingly.
I also added a config.example file.

I used apt provided mktorrent, which seems to be working without problem.
Why did you ask to clone latest version in the README.md ?

Image is 177MB.

I hope it can help!

### CODE REVIEW

**Comment by iw00t** [comment]
Thank you for your contribution. I'm getting back round to these projects now! :)

Could you please resolve the conflicts and I'll test this and merge?

**Comment by uZer** [comment]
Hey, sorry I abandoned this PR months ago, it's now rebased!

**Comment by gotson** [comment]
I've been trying to toy with this, but I don't understand how it can work, since within the container the paths are not the actual paths on the filesystem, so the torrent references paths _inside_ the container.

It can only work if your torrent client is using the _exact_ same volume mount.

**Comment by gotson** [comment]
I've done a few changes to make it work better, basically to authorize command line arguments, so you can run it with `-U` or with a specific URL if needed.

I also removed the build steps from the `docker-compose.yml`, as the image would be published on DockerHub anyway.

I'll prepare a PR based on this one, with my enhancements, and i'll add a CI step with Github Actions to automatically build and push the image, so any upcoming code change would reflect on the published image.

**Comment by uZer** [comment]
OK great!

**Pull request merged**
